# Generated by Django 6.0.1 on 2026-01-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级/教室名称')),
                ('rows', models.IntegerField(default=6, verbose_name='行数')),
                ('cols', models.IntegerField(default=8, verbose_name='列数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='学号')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True, verbose_name='性别')),
                ('score', models.FloatField(default=0, help_text='用于按成绩排座', verbose_name='成绩')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='seats.classroom', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(verbose_name='行')),
                ('col', models.IntegerField(verbose_name='列')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seats.classroom')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_seat', to='seats.student', verbose_name='入座学生')),
            ],
            options={
                'verbose_name': '座位',
                'verbose_name_plural': '座位',
                'ordering': ['row', 'col'],
                'unique_together': {('classroom', 'row', 'col')},
            },
        ),
    ]
