# Generated by Django 6.0.1 on 2026-01-30 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='cell_type',
            field=models.CharField(choices=[('seat', '座位'), ('aisle', '走廊'), ('podium', '讲台'), ('empty', '空位')], default='seat', max_length=10, verbose_name='单元类型'),
        ),
        migrations.CreateModel(
            name='SeatConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('must_seat', '指定座位'), ('forbid_seat', '禁用座位'), ('must_row', '指定行'), ('forbid_row', '禁用行'), ('must_col', '指定列'), ('forbid_col', '禁用列'), ('must_together', '指定相邻'), ('forbid_together', '禁止相邻')], max_length=20, verbose_name='约束类型')),
                ('row', models.IntegerField(blank=True, null=True, verbose_name='行')),
                ('col', models.IntegerField(blank=True, null=True, verbose_name='列')),
                ('distance', models.PositiveIntegerField(default=1, verbose_name='距离')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=120, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='seats.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='seats.student', verbose_name='学生')),
                ('target_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_constraints', to='seats.student', verbose_name='关联学生')),
            ],
            options={
                'verbose_name': '排座约束',
                'verbose_name_plural': '排座约束',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='小组名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='seats.classroom')),
            ],
            options={
                'verbose_name': '小组',
                'verbose_name_plural': '小组',
                'ordering': ['order', 'created_at'],
                'unique_together': {('classroom', 'name')},
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='seats.seatgroup', verbose_name='所属小组'),
        ),
        migrations.CreateModel(
            name='LayoutSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='布局名称')),
                ('data', models.JSONField(verbose_name='布局数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_snapshots', to='seats.classroom')),
            ],
            options={
                'verbose_name': '布局快照',
                'verbose_name_plural': '布局快照',
                'ordering': ['-created_at'],
                'unique_together': {('classroom', 'name')},
            },
        ),
    ]
