# Generated by Django 6.0.1 on 2026-02-12 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_seat_cell_type_seatconstraint_seatgroup_seat_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatgroup',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_group', to='seats.student', verbose_name='组长'),
        ),
    ]
