# Generated by Django 6.0.2 on 2026-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0007_futuremodeconfig_thinking_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendKVStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='键')),
                ('value', models.TextField(blank=True, default='', verbose_name='值')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '前端配置',
                'verbose_name_plural': '前端配置',
            },
        ),
    ]
