# Generated by Django 6.0.6 on 2026-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0014_student_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True, verbose_name='会话 key')),
                ('cloud_uid', models.CharField(blank=True, default='', max_length=64, verbose_name='云端 UID')),
                ('seen', models.BooleanField(default=False, verbose_name='已看过新手引导')),
                ('completed_steps', models.CharField(blank=True, default='', max_length=120, verbose_name='已完成步骤')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '新手引导状态',
                'verbose_name_plural': '新手引导状态',
            },
        ),
    ]
