from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_classroom, name='create_classroom'),
    path('classroom/<int:pk>/', views.classroom_detail, name='classroom_detail'),
    path('classroom/<int:pk>/layout/', views.layout_editor, name='layout_editor'),
    path('classroom/<int:pk>/layout/grid/', views.update_layout_grid, name='update_layout_grid'),
    path('classroom/<int:pk>/state/', views.classroom_state, name='classroom_state'),
    path('classroom/<int:pk>/import/', views.import_students, name='import_students'),
    path('classroom/<int:pk>/export/', views.export_students, name='export_students'),
    path('classroom/<int:pk>/move/', views.move_student, name='move_student'),
    path('classroom/<int:pk>/seat/clear/', views.clear_seat, name='clear_seat'),
    path('classroom/<int:pk>/seat/assign/', views.assign_student, name='assign_student'),
    path('classroom/<int:pk>/student/<int:student_id>/delete/', views.delete_student, name='delete_student'),
    path('classroom/<int:pk>/cell/update/', views.update_cell_type, name='update_cell_type'),
    path('classroom/<int:pk>/group/create/', views.create_group, name='create_group'),
    path('classroom/<int:pk>/group/<int:group_id>/delete/', views.delete_group, name='delete_group'),
    path('classroom/<int:pk>/group/<int:group_id>/rename/', views.rename_group, name='rename_group'),
    path('classroom/<int:pk>/group/assign/', views.assign_group, name='assign_group'),
    path('classroom/<int:pk>/group/assign/batch/', views.assign_group_batch, name='assign_group_batch'),
    path('classroom/<int:pk>/group/export/', views.export_group_report, name='export_group_report'),
    path('classroom/<int:pk>/constraint/create/', views.create_constraint, name='create_constraint'),
    path('classroom/<int:pk>/constraint/<int:constraint_id>/delete/', views.delete_constraint, name='delete_constraint'),
    path('classroom/<int:pk>/arrange/', views.auto_arrange_seats, name='auto_arrange_seats'),
    path('classroom/<int:pk>/layout/save/', views.save_layout_snapshot, name='save_layout_snapshot'),
    path('classroom/<int:pk>/layout/<int:snapshot_id>/load/', views.load_layout_snapshot, name='load_layout_snapshot'),
    path('classroom/<int:pk>/layout/<int:snapshot_id>/delete/', views.delete_layout_snapshot, name='delete_layout_snapshot'),
    path('classroom/<int:pk>/layout/export/', views.export_seats_file, name='export_seats_file'),
    path('classroom/<int:pk>/layout/import/', views.import_seats_file, name='import_seats_file'),
    path('classroom/<int:pk>/undo/', views.undo_action, name='undo_action'),
    path('classroom/<int:pk>/redo/', views.redo_action, name='redo_action'),
    path('classroom/<int:pk>/delete/', views.delete_classroom, name='delete_classroom'),
    path('classroom/<int:pk>/suggestion/apply/', views.apply_suggestion, name='apply_suggestion'),
    path('classroom/<int:pk>/suggestion/dismiss/', views.dismiss_suggestion, name='dismiss_suggestion'),
]
